markdown: kramdown
safe: true
lsi: false
highlighter: rouge
permalink: /:year/:month/:day/:title/
title: "Know It Not"
production_url: "http://www.knowitnot.com"
description: "Things you may want to know, but don't"
disqus_shortname: "knowitnotdotcom"
exclude: [Gemfile, Gemfile.lock, gems, _assets, bower_components]
author:
  name: "Jason Barnett"
  twitter: "jwbiam1"
  github: "jasonwbarnett"
  linkedin: "jasonwbarnett"
  email: "jason@knowitnot.com"
defaults:
  - scope:
      path: "" # empty string for all files
    values:
      layout: "post"
      author: "Jason Barnett"
