markdown: rdiscount
safe: true
lsi: false
pygments: true
permalink: /:year/:month/:day/:title/
title : Know It Not
production_url : http://knowitnot.com
description: "Things you may want to know, but don't"
disqus_shortname: knowitnotdotcom
analytics: UA-37806223-1
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
author :
  name : Jason Barnett
  github : jasonwbarnett
  twitter : jasonwbarnett
  facebook: jasonwbarnett
  email: jason@knowitnot.com
